### ISSUE TITLE
convert .ipython notebooks to python scripts

### ISSUE THREAD

**Issue by zifn** [zifn/qchem_nitrobenzene#3]
Right now the ipython notebooks do the math more or less correctly but they are a little time consuming to use due to non-automated parsing and function calling. To facilitate this, the notebook needs to be converted into normal python modules with parsing integrated with the rest of the program. A bash file could be used to pipe the dalton output to the python input file

**Comment by RThurston-lbl** [comment]
Bash file not introduced. Will be added next round as needed. Notebook converted to python scripts
